### ISSUE TITLE
RNN Bench results poor on P100 vs M40 - doubt

### ISSUE THREAD

**Issue by arundasan91** [baidu-research/DeepBench#27]
Hello,

I ran the RNN-bench on both an M40 and P100 GPU. Results shows that the Vanilla RNN TeraFLOPS result for P100 is lesser than M40 GPU. 

LSTM values are better. 

Do you have any insights on this ? Have you guys faced this issue ? I re-ran the benchmark but got similar results. Conv bench and GEMM bench results are favoring P100 by a huge margin.

<img width="394" alt="screen shot 2017-03-08 at 9 21 09 pm" src="https://cloud.githubusercontent.com/assets/14352842/23734512/2e4eb762-0445-11e7-87cf-ae9278eae6df.png">

Thanks,
Arun

**Comment by sharannarang** [comment]
Arun,

It's certainly surprising that the RNN benchmark on P100 performs worse. It's possible that Nvidia has spent more time optimizing cuDNN kernels for LSTMs rather than RNNs. Can you also confirm the SM version used for these runs? Please feel free to submit these results by adding a new spreadsheet in the `results` folder. 

We should also have a few P100s running sometime next month. So, I should be able to run the benchmark on them and confirm the numbers.

**Comment by arundasan91** [comment]
I will clean the results file and will upload it soon. Bt the way, I am running the benchmarks in an OpenStack baremetal cloud instance. Its is one of our lab's cloud testbed. Do you accept results from such a cloud environment ?

Thanks,
Arun

**Comment by sharannarang** [comment]
I think the single GPU benchmarks such as `gemm`, `convolution` and rnn kernels should be fine. The all reduce benchmark might be a bit tricky since the hardware will be configured differently. 

We also are setting up some P100 in our cluster, so we should have results soon to compare with your numbers.

**Comment by arundasan91** [comment]
Thank you @sharannarang. I will update the results soon.

**Comment by sharannarang** [comment]
Hi @arundasan91 ,

I just ran the RNN benchmark on P100 using `cudnn` v6. Here are the plots for forward and backward TFlops. The P100 does better than the M40 for most cases. It's slightly worse for a few of the kernels. But these results are better than the ones you posted. Perhaps, you need to use a newer `cudnn` version. I'll submit the results soon to DeepBench, so you can look at the numbers. 

![image](https://cloud.githubusercontent.com/assets/7253756/26658576/c922e2f6-461f-11e7-81bf-e6e55bd4e0b5.png)

![image](https://cloud.githubusercontent.com/assets/7253756/26658584/d07e2240-461f-11e7-8767-db74d22bdbe8.png)

![image](https://cloud.githubusercontent.com/assets/7253756/26658588/d76e3f9a-461f-11e7-8d55-c921505390bc.png)
![image](https://cloud.githubusercontent.com/assets/7253756/26658589/db3578f0-461f-11e7-9633-6063303f662b.png)

**Comment by arundasan91** [comment]
I will definitely take a look at the results and CUDNN version at my end. Thanks a lot Sharan.

**Comment by arundasan91** [comment]
I ran the benchmarks on CUDNN 5.1. Did not try V6 since it was not supported by some DL frameworks I was using.

**Comment by sharannarang** [comment]
Yeah, DL typically frameworks need some time to support the latest version of cuDNN. However, I think it makes sense to report numbers with the latest drivers on DeepBench. 

I'm closing this issue. Feel free to reopen in case you have any questions/concerns.
