### ISSUE TITLE
Computation complexity of operators

### ISSUE THREAD

**Issue by TaoLv** [baidu-research/DeepBench#55]
I have noticed that a formulation is used to calculate the TFLOPS of each operator in the XLS files. 
For recurrent layers - LSTM, it is calculated as `=(8*$E296*$D296*$C296*$C296)/(G296/1000)/10^12`.
It seems it just includes the computation of GEMM, and doesn't include compution of sigmoid or tanh.
Could you explain the formulation more detaily, especially for LSTM/GRU items. Thanks.

**Comment by sharannarang** [comment]
@TaoLv ,

For recurrent layers, the majority of the FLOPS are spent in the recurrent GEMMs. This is particularly true if we use approximations of the nonlinearities instead of accurate implementations. More details regarding these approximations can be found in the appendix of the [DeepVoice](https://arxiv.org/pdf/1702.07825.pdf) paper. Most frameworks typically implement these non linearities using approximations. Therefore, we've only included the GEMM computation in FLOPS calculation. Hope this helps.

**Comment by TaoLv** [comment]
I see. Thanks for your kindly reply. @sharannarang
