### ISSUE TITLE
confusion regarding parameters used in Excel sheet

### ISSUE THREAD

**Issue by hit1001** [baidu-research/DeepBench#7]
Hi,
While looking at the results, i came across forward(ms)  w.rt inputs and parameters. What does that actually mean? Does it mean testing the forward pass with changes in the image size while doing a forward pass? 
If i get some insight into how exactly the excel file mean? Thanks.

**Comment by sharannarang** [comment]
The convolution results have three columns: 

```
forward (ms): Time required for the forward pass through the network in milliseconds. 
wrt params (ms):  Time required for the backward pass wrt parameters through the network in milliseconds.
wrt inputs (ms):  Time required for the backward pass wrt inputs through the network in milliseconds.
```
All the kernels are run for forward and backward passes. In some cases, backward wrt inputs are not reported because those kernels are typically the inputs of the network. These are indicated in the spreadsheets. 

I hope that clarifies the results. Please let me know if you have any questions.

**Comment by sharannarang** [comment]
I'm closing this for now. Please feel free to reopen if you have any other questions.

**Comment by hit1001** [comment]
What could be possobily explanation for parameters such as P and Q? Are  they parameters from the different algorithms?
